services:
  minio:
    image: minio/minio
    container_name: poc_minio_spb3
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: scfc@12345
    command: server /data --console-address ":9001" --address ":9000"
    restart: always
volumes:
  minio_data:
    driver: local